package com.goodvote.client.screen;

import com.goodvote.network.GoodVotePackets;
import com.goodvote.network.PluginBridgePayload;
import com.goodvote.vote.VoteChoice;
import net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking;
import net.minecraft.client.gui.DrawContext;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.gui.widget.ButtonWidget;
import net.minecraft.text.Text;

import java.util.UUID;

/**
 * Vote screen GUI - shown to players when a vote is active.
 * Displays vote info, countdown, and Accept/Reject/Abstain buttons.
 */
public class VoteScreen extends Screen {
    private final GoodVotePackets.OpenVotePayload initialData;
    private UUID sessionId;
    private int voteType;
    private String initiatorName;
    private String content;
    private long remainingMs;
    private int eligibleCount;
    private int acceptCount;
    private int rejectCount;
    private int abstainCount;
    private boolean hasVoted;
    private int playerVoteChoice; // -1 = not voted
    private boolean showResult;
    private boolean resultPassed;
    private long lastUpdateTime;
    private boolean bridgeMode; // true when connected to Paper plugin via bridge

    // Buttons
    private ButtonWidget acceptButton;
    private ButtonWidget rejectButton;
    private ButtonWidget abstainButton;

    public VoteScreen(GoodVotePackets.OpenVotePayload data) {
        super(Text.literal("投票"));
        this.initialData = data;
        this.sessionId = data.sessionId();
        this.voteType = data.voteType();
        this.initiatorName = data.initiatorName();
        this.content = data.content();
        this.remainingMs = data.remainingMs();
        this.eligibleCount = data.eligibleCount();
        this.acceptCount = data.acceptCount();
        this.rejectCount = data.rejectCount();
        this.abstainCount = data.abstainCount();
        this.hasVoted = data.hasVoted();
        this.playerVoteChoice = data.playerVoteChoice();
        this.lastUpdateTime = System.currentTimeMillis();
        this.showResult = false;
        // Detect bridge mode: if sessionId was generated by PluginBridgeHandler
        this.bridgeMode = PluginBridgeHandler.isBridgeSession(sessionId);
    }

    @Override
    protected void init() {
        super.init();

        int centerX = this.width / 2;
        int centerY = this.height / 2;
        int buttonWidth = 100;
        int buttonHeight = 20;
        int buttonSpacing = 10;

        // Accept button (green)
        acceptButton = ButtonWidget.builder(Text.literal("✓ 允许"), btn -> castVote(VoteChoice.ACCEPT))
                .dimensions(centerX - buttonWidth - buttonSpacing, centerY + 40, buttonWidth, buttonHeight)
                .build();

        // Reject button (red)
        rejectButton = ButtonWidget.builder(Text.literal("✗ 拒绝"), btn -> castVote(VoteChoice.REJECT))
                .dimensions(centerX - buttonWidth / 2, centerY + 40, buttonWidth, buttonHeight)
                .build();

        // Abstain button (gray)
        abstainButton = ButtonWidget.builder(Text.literal("○ 弃权"), btn -> castVote(VoteChoice.ABSTAIN))
                .dimensions(centerX + buttonSpacing, centerY + 40, buttonWidth, buttonHeight)
                .build();

        updateButtonStates();

        this.addDrawableChild(acceptButton);
        this.addDrawableChild(rejectButton);
        this.addDrawableChild(abstainButton);
    }

    private void castVote(VoteChoice choice) {
        if (hasVoted) return;
        if (bridgeMode) {
            // Send vote through plugin bridge channel to Paper plugin
            ClientPlayNetworking.send(new PluginBridgePayload("vote:" + choice.name()));
        } else {
            // Send vote through Fabric server channel
            ClientPlayNetworking.send(new GoodVotePackets.CastVotePayload(sessionId, choice.toId()));
        }
        hasVoted = true;
        playerVoteChoice = choice.toId();
        updateButtonStates();
    }

    public void updateVote(GoodVotePackets.VoteUpdatePayload update) {
        this.acceptCount = update.acceptCount();
        this.rejectCount = update.rejectCount();
        this.abstainCount = update.abstainCount();
        this.eligibleCount = update.eligibleCount();
        this.remainingMs = update.remainingMs();
        this.hasVoted = update.hasVoted();
        this.playerVoteChoice = update.playerVoteChoice();
        this.lastUpdateTime = System.currentTimeMillis();
        updateButtonStates();
    }

    public void showResult(GoodVotePackets.VoteResultPayload result) {
        this.showResult = true;
        this.resultPassed = result.passed();
        this.acceptCount = result.acceptCount();
        this.rejectCount = result.rejectCount();
        this.abstainCount = result.abstainCount();
        this.eligibleCount = result.eligibleCount();
        updateButtonStates();
    }

    private void updateButtonStates() {
        if (acceptButton == null) return;
        boolean canVote = !hasVoted && !showResult;
        acceptButton.active = canVote;
        rejectButton.active = canVote;
        abstainButton.active = canVote;

        if (hasVoted) {
            acceptButton.setMessage(Text.literal(playerVoteChoice == 0 ? "✓ 已允许" : "✓ 允许"));
            rejectButton.setMessage(Text.literal(playerVoteChoice == 1 ? "✗ 已拒绝" : "✗ 拒绝"));
            abstainButton.setMessage(Text.literal(playerVoteChoice == 2 ? "○ 已弃权" : "○ 弃权"));
        }
    }

    @Override
    public void render(DrawContext context, int mouseX, int mouseY, float delta) {
        super.render(context, mouseX, mouseY, delta);

        int centerX = this.width / 2;
        int centerY = this.height / 2;

        // Title
        String typeStr = switch (voteType) {
            case 0 -> "管理员指令投票";
            case 1 -> "玩家请求投票";
            case 2 -> "配置变更投票";
            default -> "投票";
        };
        context.drawCenteredTextWithShadow(this.textRenderer,
                Text.literal(typeStr).withColor(0xFFAA00),
                centerX, centerY - 80, 0xFFFFFF);

        // Initiator
        context.drawCenteredTextWithShadow(this.textRenderer,
                Text.literal("发起者: " + initiatorName),
                centerX, centerY - 60, 0xAAAAAA);

        // Content
        context.drawCenteredTextWithShadow(this.textRenderer,
                Text.literal("内容: " + content).withColor(0x55FFFF),
                centerX, centerY - 40, 0xFFFFFF);

        // Countdown bar
        renderCountdownBar(context, centerX, centerY - 20);

        // Vote counts
        String voteInfo = String.format("同意: %d  拒绝: %d  弃权: %d  总人数: %d",
                acceptCount, rejectCount, abstainCount, eligibleCount);
        context.drawCenteredTextWithShadow(this.textRenderer,
                Text.literal(voteInfo),
                centerX, centerY + 20, 0xFFFFFF);

        // Result display
        if (showResult) {
            String resultText = resultPassed ? "投票已通过!" : "投票未通过";
            int color = resultPassed ? 0x55FF55 : 0xFF5555;
            context.drawCenteredTextWithShadow(this.textRenderer,
                    Text.literal(resultText).withColor(color),
                    centerX, centerY + 70, color);
        }
    }

    private void renderCountdownBar(DrawContext context, int centerX, int y) {
        int barWidth = 200;
        int barHeight = 8;
        int barX = centerX - barWidth / 2;

        // Background
        context.fill(barX, y, barX + barWidth, y + barHeight, 0xFF333333);

        // Progress
        long totalMs = remainingMs > 0 ? remainingMs + (System.currentTimeMillis() - lastUpdateTime) : 1;
        long currentRemaining = Math.max(0, remainingMs - (System.currentTimeMillis() - lastUpdateTime));
        float progress = totalMs > 0 ? (float) currentRemaining / totalMs : 0;
        int progressWidth = (int) (barWidth * progress);

        int barColor = progress > 0.5f ? 0xFF55FF55 : progress > 0.25f ? 0xFFFFAA00 : 0xFFFF5555;
        context.fill(barX, y, barX + progressWidth, y + barHeight, barColor);

        // Time text
        long seconds = currentRemaining / 1000;
        context.drawCenteredTextWithShadow(this.textRenderer,
                Text.literal(seconds + "s"),
                centerX, y + barHeight + 2, 0xFFFFFF);
    }

    @Override
    public boolean shouldPause() {
        return false; // Allow game to continue while voting
    }
}
