name: QQBridge
version: '${version}'
main: com.qqbridge.QQBridgePlugin
api-version: '1.21'
description: QQ 群服互联
author: 爱玩电脑的小融融 (ycrrongos)

commands:
  qq:
    description: 发送消息到 QQ 群
    usage: /qq <消息>

permissions:
  goodmc.qq:
    description: 发送消息到 QQ 群
    default: true
