name: GoodMC
version: '${version}'
main: com.goodmc.GoodMCPlugin
api-version: '1.21'
description: GoodMC 玩法增强
author: ycrrongos
softdepend: [AdminVote, Server-Vision]

commands:
  kill:
    description: 自杀（普通玩家）或击杀实体（管理员）
    usage: /kill [目标]
  seed:
    description: 查看世界种子
    usage: /seed
  sc:
    description: 查看 GoodMC 功能说明
    usage: /sc
  tnt_unlock:
    description: 解锁TNT丢出保护锁
    usage: /tnt_unlock
  tnt_traj:
    description: 切换TNT丢出抛物线
    usage: /tnt_traj <轨迹类型>
  tnt_gui:
    description: 打开TNT抛物线选择界面
    usage: /tnt_gui
  tnt_gui_chest:
    description: 打开TNT抛物线选择界面（箱子 GUI）
    usage: /tnt_gui_chest
  fireball_unlock:
    description: 解锁火球丢出保护锁
    usage: /fireball_unlock

permissions:
  goodmc.seed:
    description: 查看世界种子
    default: true
  goodmc.sc:
    description: 查看 GoodMC 功能说明
    default: true
